export const ERROR_ROUTINE = 'ERROR_ROUTINE'
export const LOADING_ROUTINE = 'LOADING_ROUTINE'

export const CREATE_ROUTINE = 'CREATE_ROUTINE'
export const READ_ROUTINE = 'READ_ROUTINE'
export const READ_ROUTINES = 'READ_ROUTINES'
export const UPDATE_ROUTINE = 'UPDATE_ROUTINE'
export const DELETE_ROUTINE = 'DELETE_ROUTINE'

export const CREATE_ROUTINE_SESSION = 'CREATE_ROUTINE_SESSION'
export const POP_ROUTINE_SESSION = 'POP_ROUTINE_SESSION'
