export const ERROR_EXERCISE = 'ERROR_EXERCISE'
export const LOADING_EXERCISE = 'LOADING_EXERCISE'

export const CREATE_EXERCISE = 'CREATE_EXERCISE'
export const READ_EXERCISES = 'READ_EXERCISES'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'

export const ADD_WEIGHT_EXERCISE = 'ADD_WEIGHT_EXERCISE'
export const DELETE_WEIGHT_EXERCISE = 'DELETE_WEIGHT_EXERCISE'
export const MOVE_EXERCISE = 'MOVE_EXERCISE'
