export const ERROR_DISH = 'ERROR_DISH'
export const LOADING_DISH = 'LOADING_DISH'

export const CLEAR_FILTER = 'CLEAR_FILTER'
export const FILTER_DISHES = 'FILTER_DISHES'

export const CREATE_DISH = 'CREATE_DISH'
export const READ_DISHES = 'READ_DISHES'
export const UPDATE_DISH = 'UPDATE_DISH'
export const DELETE_DISH = 'DELETE_DISH'

export const CLEAR_CURRENT_DISH = 'CLEAR_CURRENT_DISH'
export const SET_CURRENT_DISH = 'SET_CURRENT_DISH'
