export const ERROR_WEIGHT = 'ERROR_WEIGHT'
export const LOADING_WEIGHT = 'LOADING_WEIGHT'

export const CREATE_WEIGHT = 'CREATE_WEIGHT'
export const READ_WEIGHT = 'READ_WEIGHT'
export const READ_WEIGHTS = 'READ_WEIGHTS'
export const UPDATE_WEIGHT = 'UPDATE_WEIGHT'
export const DELETE_WEIGHT = 'DELETE_WEIGHT'
